catalog/urls.py
"""
 catalog/urls.py
---------------------------------------------------------------
 Url routing logic for the catalogs application.
"""
from django.urls import path
from catalog import views

# Namespaces are a honking great idea - Zen of Python
app_name='catalog'

urlpatterns = [
  path('', views.index, name='index'),
  path('book/<int:id>/<slug:slug>',views.BookDetailView.as_view(), name='book-detail'),
  path('book/',views.BookListView.as_view(),name='books'),
  path('author/', views.AuthorListView.as_view(), name='authors'),
  path('author/<int:id>/<slug:slug>', views.AuthorDetailView.as_view(), name='author-detail'),
  path('language/', views.LangListView.as_view(), name='languages'),
  path('language/<int:pk>/<str:language>' ,views.LangDetailView.as_view(), name='language-detail'),
  path('genre/', views.GenreListView.as_view(), name='genre-list'),
  path('genre/<int:pk>/<str:genre>', views.GenreDetailView.as_view(), name='genre-detail'),
  path('mybooks/', views.LoannedBooksByUserListView.as_view(), name='my-borrowed-books'),
  path('all-books/', views.AllBorrowedBooksListView.as_view(), name='all-books'),
  path('check-in/<uuid:pk>/', views.BorrowedBookDetailView.as_view(), name='check-in'),
  path('check-out/<uuid:pk>/', views.CheckoutBookInstance.as_view(), name='check-out'),
]

library/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/',include('catalog.urls')),
]

from django.views.generic import RedirectView

urlpatterns += [
  path('', RedirectView.as_view(url='/catalog/')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
"""
 catalog/models.py
 ----------------------------------------------------------
 A place to define model instances for the Catalog application.
 Remember to define SlugFields for each model we wish to represent in
 our REST API. This will allow us to provide more meaningful URLs and
 improve the SEO.
"""
from django.db import models
from django.urls import reverse

class Genre(models.Model):
    """
    Model representing a genre of literature.
    """
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey('auth.User', related_name='genres_created', null=True, on_delete=models.SET_NULL)
    modified_by = models.ForeignKey('auth.User', related_name='genres_modified', null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=200, blank=True, null=True, help_text='A genre of literature that can be applied to bookd.')

    def __str__(self):
       """
       String for representing a model object
       """
       return self.name

    def get_absolute_url(self):
      return reverse('catalog:genre-detail', kwargs={'pk': self.id, 'genre': self.name})

class Book(models.Model):
    """
    Model representing a book (but not a specific book instance.)
    """
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey('auth.User', related_name='books_created', on_delete=models.SET_NULL, null=True)
    modified_by = models.ForeignKey('auth.User', related_name='books_modified', on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=200, blank=True, null=True, db_index=True, help_text='Enter the book\'s title')
    author = models.ManyToManyField('Author')
    summary=models.TextField(blank=True, null=True, help_text='Enter a brief description of the book.')
    isbn = models.CharField('ISBN',max_length=13, blank=True, null=True, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField('Genre')
    slug = models.SlugField(max_length=30, db_index=True)

    class Meta:
        ordering = ['title', ]

    def __str__(self):
       """
       String representing a book object
       """
       return self.title

    @property
    def copies_available(self):
      return self.bookinstance_set.filter(status='a').count()

    def get_absolute_url(self):
       """
       Returns the url to access the detail record for this book.
       """
       return reverse('catalog:book-detail', kwargs={'id': str(self.id), 'slug': self.slug})

    def save(self):
       """
       Overriding default save behavior to ensure slug generation
       """
       self.slug = '-'.join(self.title.lower().split(' '))

       super(Book, self).save()

    def display_author(self):
      """
       Create string representation of the Author(s) for this book.
      """
      return ', '.join([f'{author.first_name} {author.last_name}' for author in self.author.all()])
    display_author.short_description = 'Author(s)'

    def display_genre(self):
       """
       Creating a string representation of the genre(s) for this book.
       """
       return ', '.join(genre.name for genre in self.genre.all())
    display_genre.short_description='Genre(s)'


import uuid # Required for uique book instance
from datetime import date
class BookInstance(models.Model):
    """
    Model representing a specific physical (or digital) copy of a book.
    """
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey('auth.User', related_name='instances_created', on_delete=models.SET_NULL, null=True)
    modified_by = models.ForeignKey('auth.User', related_name='instances_modified', on_delete=models.SET_NULL, null=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this book across the entire library')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200, blank=True, null=True, help_text='The publisher\'s trade name.')
    due_date = models.DateField(null=True, blank=True, db_index=True, help_text='The date this book is due back (if checked out).')
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True, related_name='books')
    borrower = models.ForeignKey('auth.User', on_delete=models.SET_NULL, null=True, blank=True, related_name='borrowed_books')

    LOAN_STATUS = (
      ('m', 'Maintenance'),
      ('o', 'On Loan'),
      ('a', 'Available'),
      ('r', 'Reserved'),
    )
    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, null=True, default='m',help_text='Book availability')


    @property
    def is_overdue(self):
      if self.due_date and date.today() >self.due_date:
        return True
      return False

    class Meta:
      ordering = ['due_date', ]
      permissions = (
        ('can_mark_returned', 'Mark books as returned'),
      )

    def __str__(self):
       """
       String representing specific book instance.
       """
       return f'{self.id} - {self.book.title}'

class Author(models.Model):
    """
    Model representing an author
    """
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey('auth.User', related_name='authors_created', on_delete=models.SET_NULL, null=True)
    modified_by = models.ForeignKey('auth.User', related_name='authors_modified', on_delete=models.SET_NULL, null=True)
    first_name = models.CharField(max_length=100, blank=True, null=True, help_text='The first name of the author.')
    last_name = models.CharField(max_length=100, blank=True, db_index=True, null=True, help_text='The last name of the author.')
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    slug = models.SlugField(max_length=50, db_index=True)

    class Meta:
      ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
       """
       Return the url to access this particular author instance.
       """
       return reverse('catalog:author-detail', kwargs={'id': str(self.id), 'slug': self.slug})

    def __str__(self):
       """
       String representing the author object
       """
       return f'{self.last_name}, {self.first_name}'

    def save(self):
      if not self.slug:
        self.slug = f'{self.first_name}-{self.last_name}'
      super(Author, self).save()


class Language(models.Model):
    """
    A model to define the languages a book instance may be written in.
    """
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey('auth.User', related_name='languages_created', on_delete=models.SET_NULL, null=True)
    modified_by = models.ForeignKey('auth.User', related_name='languages_modified', on_delete=models.SET_NULL, null=True)
    language = models.CharField(max_length=100, blank=True, null=True, help_text='A human language a particular book isntances is written in.')

    def __str__(self):
       """
       String representing the language
       """
       return self.language

    def get_absolute_url(self):
      return reverse('catalog:language-detail', kwargs={'pk': str(self.id), 'language': self.language})

catalog/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from catalog.models import Author, Book, BookInstance, Genre, Language
import datetime



def index(request):
  """
   A simple rendering of the library homepage.
  """
  context = {
  'user': request.user,
  'num_authors': Author.objects.all().count(),
  'num_books': Book.objects.all().count(),
  'num_instances': BookInstance.objects.all().count(),
  'num_languages': Language.objects.all().count(),
  'num_genres': Genre.objects.all().count()}

  # Getting the number of times a specfici user (browser) has visited this site.
  num_visits = request.session.get('num_visits', 0)
  request.session['num_visits'] = num_visits +1

  context['num_visits'] = num_visits
  return render(request, template_name='catalog/index.html', context=context)

# Transitioning to class based, generic views because of the wonderful brevity of code required.
class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    paginate_by = 5


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book


class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author
    paginate_by = 5

class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
  model = Author

class LangListView(LoginRequiredMixin, generic.ListView):
  model = Language

class LangDetailView(LoginRequiredMixin, generic.DetailView):
  model = Language

class GenreListView(LoginRequiredMixin, generic.ListView):
  model = Genre

class GenreDetailView(LoginRequiredMixin, generic.DetailView):
    model = Genre

class LoannedBooksByUserListView(LoginRequiredMixin, generic.ListView):
  """
   Generic CBV for listing books on loan to current user.
  """
  model = BookInstance
  template_name = 'catalog/bookinstance_list_borrowed_user.html'
  paginate_by = 5

  def get_queryset(self):
    return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_date')

class AllBorrowedBooksListView(PermissionRequiredMixin, generic.ListView):
  permission_required = 'can_mark_returned'
  # I'm going a slightly more convoluated route and organising our borrowed books by User.  I think this would allow librarians to spot repeat offenders easier.
  model = User
  paginate_by = 5
  template_name='catalog/all_borrowed_books.html'

  def get_queryset(self):
    return User.objects.filter(borrowed_books__isnull=False).distinct()

class BorrowedBookDetailView(PermissionRequiredMixin, generic.DetailView):
  """
   The purpose for this CBV is really a custom POST method that allows a librarian to check books back into stock.
  """
  permission_required='can_mark_returned' # only librarians have this permission
  model = BookInstance

  def post(self, request, *args, **kwargs):
    """
     Checking a book in.
    """
    book_inst = self.get_object()
    book_inst.status = 'a' # Marking the book as available
    book_inst.due_date = None # Setting the due date to None
    book_inst.borrower = None # Setting the borrower to Nonen
    book_inst.save()
    return HttpResponseRedirect(reverse('catalog:all-books'))

class CheckoutBookInstance(LoginRequiredMixin, generic.DetailView):
  """
   The purpose for this CBV is a custom POST method that allows library patrons (and librarians) to check out books.
  """
  model = BookInstance

  def post(self, request, *args, **kwargs):
    """
     Checking out a book.
    """
    # Setting a 2 week period a patron can check a book out for.
    checkout_period = datetime.timedelta(weeks=2)
    book_inst = self.get_object()
    book_inst.status = 'o'
    book_inst.due_date = datetime.date.today() + checkout_period
    book_inst.borrower = request.user
    book_inst.save()
    return HttpResponseRedirect(reverse('catalog:my-borrowed-books'))

catalog/templates/catalog/all_borrowed_books.html
{% extends "catalog/base_index.html" %}
{% block more_style %}

{% endblock %}

{% block content %}
<h3>All Borrowed Books by Library Patron</h3>
<hr>
{% for user in user_list %}
    <h5 class="mt-2">{{user.first_name}} {{user.last_name}}:</h5>
    {% for bookinst in user.borrowed_books.all  %}
        <div class="row">
            <div class="col s4 align-left">
                <strong>{{bookinst.book.title}}</strong>
            </div>
            <div class="col s8 align-right">
                <span class="{% if bookinst.is_overdue %}overdue{% endif %}">Due Date: {{bookinst.due_date}}
                    <form class="right" action="{% url 'catalog:check-in' bookinst.id %}" method="post">
                        {% csrf_token %}
                        <button class="btn-floating btn-small waves-effect waves-light gd-brightblue" name="button"> <i class="small material-icons">check</i> </button>
                    </form>
                </span>
            </div>
        </div>
        <hr>
    {% endfor %}
{% empty %}
    <h4>No one has checked out any books!  This means your library is not really fulfilling it's function.</h4>
{% endfor %}
{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "catalog/base_index.html" %}

{% block content %}
    <div class="row">
        <div class="col s12">
            <div class="card ">
                <span class='card-title'>{{author.first_name}} {{author.last_name}}</span>
                <div class="divider">

                </div>
                <p><strong>Date of Birth:</strong> {{author.date_of_birth}}</p>
                {% if author.date_of_death %}
                <p><strong>Date of Death:</strong> {{author.date_of_death}}</p>
                {% endif %}
            </div>
        </div>
        <div class="col s11 offset-s1">
            <h4>Books by this Author: </h4>
            {% for book in author.book_set.all %}
                <div class="card z-depth-1 ">
                    <span class="card-title">
                        {{book.title}}
                    </span>
                
                    <p>{{book.summary}}</p>
                    <div class="card-action">
                        <a href="{{book.get_absolute_url}}" class='btn gd-tealblue waves-effect waves-light hoverable'>Book Details</a>
                    </div>
                </div>
            {% empty %}
                <div class="card red darken-2 white-text">
                    <span class='card-title'>No Books by This Author</span>
                    <p>I wonder why we even have a record of this person.</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "catalog/base_index.html" %}

{% block content %}
    <h3>Author List</h3>

    {% for author in author_list %}
        {% if forloop.first %}
            <div class="collection">
        {% endif %}
        <li class="collection-item"><a href="{{author.get_absolute_url}}">{{author.last_name}}, {{author.first_name}}</a> ({{author.date_of_birth}} - {{author.date_of_death}})</li>
        {% if forloop.last %}
            </div>
        {% endif %}
    {% empty %}
        <h4>No Books!</h4>
        <div class="divider"> </div>
        <p>This is very sad.  What is a library without books?</p>
    {% endfor %}
{% endblock %}

catalog/templates/catalog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>{{title|default:"Local Library"}}</title>
        <link rel="stylesheet" href='{% static "materialize/css/materialize.css" %}'>
          <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href=' {% static "css/main.css" %} '>
        {% block more_style %}

        {% endblock %}
    </head>
    <body>
        {% block body %}

        {% endblock %}
        <script src='{% static "materialize/js/materialize.js" %}'>   </script>
        {% block more_scripts %}

        {% endblock %}
    </body>
</html>

catalog/templates/catalog/base_index.html
{% extends "catalog/base.html" %}

{% block more_style %}
<style media="screen">
  .mt-5 {
      margin-top: 5em;
  }
  .mt-4 {
      margin-top: 4em;
  }
  .mt-3{
      margin-top: 3em;
  }
</style>
{% endblock %}

{% block body %}

<div class="container">
    <section class="center-align">
        <h2 class="">Welcome {% if user %}{{user.first_name}}{% endif %} to your Local Library</h2>
    </section>
    <div class="divider">

    </div>
    <div class="row">
        <!-- Navigation Panel -->
        <div class="col s4 ">
            {% block sidebar %}
                <div class="collection ">
                    <a href="{% url 'catalog:index'%}" class="collection-item black-text ">Home</a>
                    {% if user.is_staff %}
                    <a class='collection-item black-text' href="{% url 'admin:index' %}">Admin</a>
                    {% endif %}
                    {% if user.is_authenticated%}
                        <a class='collection-item black-text' href="{% url 'logout' %}">Logout</a>
                        <a class="collection-item black-text" href="{% url 'catalog:my-borrowed-books' %}">My Borrowed Books</a>
                    {% else %}
                        <a class='collection-item black-text' href="{% url 'login' %}">Login</a>
                    {% endif %}
                    <a href="{% url 'catalog:authors' %}" class="collection-item black-text"><span class=" badge">{{num_authors}}</span>All Authors</a>
                    <a href="{% url 'catalog:books' %}" class="collection-item black-text"><span class=" badge">{{num_books}}</span>All Books</a>
                    <a href="{% url 'catalog:languages' %}" class="collection-item black-text"><span class=" badge">{{num_languages}}</span>All Languages</a>
                    <a href="{% url 'catalog:genre-list' %}" class="collection-item black-text"><span class=" badge">{{num_genres}}</span>All Genres</a>
                </div>
                {% if perms.catalog.can_mark_returned %}
                <hr>
                <div class="mt-3">
                    <h4>Library Admin Actions</h4>
                    <!-- TODO:  Write a template allowing  users with proper permissions to mark books as returned -->
                    <div class="collection">
                        <a class="collection-item waves-effect waves-light gd-aquadark white-text" href="{% url 'catalog:all-books' %}">All Loaned Books</a>
                    </div>
                </div>
                {% endif %}
            {% endblock %}
        </div>
        <div class="col s8">
            <!-- page content -->
            {% block content %}{% endblock %}
            {% block pagination %}
                {% if is_paginated %}
                <!-- Pagination Section -->
                    <ul class='pagination center-align'>
                        <li class='waves effect {% if not page_obj.has_previous %} disabled{% endif %}'><a href="{% if page_obj.has_previous %}{{request.path}}?page={{page_obj.previous_page_number}}{% endif %} "><i class='material-icons'>chevron_left</i></a></li>
                        <li><span class="badge">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}</span> </li>
                        <li class="waves effect {% if not page_obj.has_next %}disabled{% endif %}"><a href=" {% if page_obj.has_next %}{{request.path}}?page={{page_obj.next_page_number}}{% endif %} "><i class="material-icons">chevron_right</i> </a> </li>
                    </ul>
                {% endif %}
            {% endblock %}
        </div>
    </div>
</div>
<footer class='gd-morebluer '>
    <span>© 2018 C. Ryan Manzer </span>
</footer>
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "catalog/base_index.html" %}

{% block content %}
    <div class="row">
        <div class="col s12 ">
            <h3 class="grey lighten-3"><strong>Title:</strong> {{book.title}}</h3>
            <div class="divider"></div>
            <h5><strong>Author:</strong> {{book.display_author}}</h5>
            <p><strong>Genre:</strong> {{book.display_genre}} </p>
            <p><strong>Summary</strong> </p>
            <p>{{book.summary}}</p>
            <small>{{book.isbn}}</small>
        </div>
    </div>
    <div class="row">
        <div class="col s10 offset-s2">
            <h4>Copies:</h4>
            <div class="container">
                {% for inst in book.bookinstance_set.all %}
                    <li class="collection-item">
                        <span>Status: </span>
                        <span class="title {% if inst.status == 'a' %}green-text darken-1 {% elif inst.status == 'm' %}red-text darken-1 {% else %} text-orange {% endif %}"> {{inst.get_status_display}}</span>
                        {% if inst.status != 'a' %} <p><strong> Due Date: </strong> {{inst.due_date}}</p> {% endif %}
                        <p><strong>Imprint: </strong>{{inst.imprint}} </p>
                        {% if inst.status == 'a' %}
                        <form class="" action="{% url 'catalog:check-out' inst.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-block waves-effect waves-dark gd-brightorange">Check Out</button>
                        </form>
                        {% endif %}
                        <small class="text-grey lighten-1">Copy ID: {{inst.id}}</small>
                    </li>
                    {% if not forloop.last %}
                    <br>
                    <div class="divider">
                    </div>
                    <br>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "catalog/base_index.html" %}

{% block content %}
    <h3>Book List</h3>

    {% for book in book_list %}
        {% if forloop.first %}
            <div class="collection">
        {% endif %}
        <li class="collection-item"><a href="{{book.get_absolute_url}}">{{book.title}}</a> ({{book.display_author}})  -  {{book.copies_available}} available</li>
        {% if forloop.last %}
            </div>
        {% endif %}
    {% empty %}
        <h4>No Books!</h4>
        <div class="divider"> </div>
        <p>This is very sad.  What is a library without books?</p>
    {% endfor %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "catalog/base_index.html" %}

{% block more_style %}

{% endblock %}
{% block content %}
    <h2> Borrowed Books</h2>

    {% for bookinst  in bookinstance_list  %}
        {% if forloop.first %}
            <ul class="">
        {% endif %}
            <li class ="my-2  {% if bookinst.is_overdue %}overdue{% endif %}">
                <a href="{{bookinst.book.get_absolute_url}}">{{bookinst.book.title}}</a> <span class='right {% if bookinst.is_overdue %} overdue {% endif %}'>Due Back:  {{bookinst.due_date}}</span>
            </li>
            <div class="divider"></div>
        {% if forloop.last %}
            </ul>
        {% endif %}
    {% empty %}
        <h4>You have no borrowed books.</h4>
    {% endfor %}
{% endblock %}

catalog/templates/catalog/genre_detail.html
{% extends "catalog/base_index.html" %}

{% block content %}
    <div class="row">
        <div class="col s12">
            <h3>{{genre}}</h3>
        </div>
        <div class="col s11 offset-s1">
            <h4>{{genre}}Books: </h4>
            {% for book in genre.book_set.all %}
                <div class="card z-depth-1 ">
                    <span class="card-title">
                        {{book.title}}
                    </span>

                    <p>{{book.summary}}</p>
                    <div class="card-action">
                        <a href="{{book.get_absolute_url}}" class='btn gd-tealblue waves-effect waves-light hoverable'>Book Details</a>
                    </div>
                </div>
            {% empty %}
                <div class="card red darken-2 white-text">
                    <span class='card-title'>No Books in this Language</span>
                    <p>I wonder why we even have a record of this.</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/genre_list.html
{% extends "catalog/base_index.html" %}

{% block content %}
    <h3>Genre List</h3>

    {% for genre in genre_list %}
        {% if forloop.first %}
            <div class="collection">
        {% endif %}
        <li class="collection-item"><a href="{{genre.get_absolute_url}}">{{genre}}</li>
        {% if forloop.last %}
            </div>
        {% endif %}
    {% empty %}
        <h4>No Genres!</h4>
        <div class="divider"> </div>
        <p>That's weird</p>
    {% endfor %}
{% endblock %}

catalog/templates/catalog/index.html
{% extends "catalog/base_index.html" %}

{% block content %}
    <p>This is a very basic Django page, built based upon the Mozilla Developer Network tutorial.</p>
    <p>  I find I continue to revise my ideas for how best to implement Django solutions by re-working simple tutorials.  This provides me a simple app in which to try out new implementation ideas where the logic of all the interconnected parts is minimal. </p>
    <p>The little tidbit about passing additioal options in the URL mappings to route multiple URLs to the same view with slighlty different behavior in Section 6 is a real gem and I'm sure I'll have a use for it soon.</p>
    <p>Another idea worth a little testing is changing the session in the Django server side code and having a JavaScript listener detect the change and respond.  While this wouldn't be as robust as using Django Channels, it would allow the updating of small UI components like the Upload Status of a file.</p>
    <div class="divider">
    </div>
    <div class="row">
        <div class="col s6 ">
            <!-- Author Card -->
            <div class="card hoverable  small z-depth-2">
                <div class="card-content ">
                    <span class='card-title'>Authors</span>
                    <p>Review our {{num_authors}} authors using the button below</p>
                </div>

                <div class="card-action blue-grey darken-1">
                    <a class="waves-effect waves-light btn gd-brightorange" href="{% url 'catalog:authors' %}">Author List</a>
                </div>
            </div>
        </div>
        <div class="col s6 ">
            <!-- Books Card -->
            <div class="card hoverable  small z-depth-2">
                <div class="card-content ">
                    <span class="card-title">Books</span>
                    <p>Review our {{num_books}} books using the button below.</p>
                </div>
                <div class="card-action blue-grey darken-1">
                    <a href="{% url 'catalog:books' %}" class="waves-effect waves-light btn gd-brightblue">Books List</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/language_detail.html
{% extends "catalog/base_index.html" %}

{% block content %}
    <div class="row">
        <div class="col s12">
            <h3>{{language.language}}</h3>
        </div>
        <div class="col s11 offset-s1">
            <h4>Books in {{language.language}}: </h4>
            {% for bi in language.books.all %}
                <div class="card z-depth-1 ">
                    <span class="card-title">
                        {{bi.book.title}}
                    </span>

                    <p>{{bi.book.summary}}</p>
                    <div class="card-action">
                        <a href="{{bi.book.get_absolute_url}}" class='btn gd-tealblue waves-effect waves-light hoverable'>Book Details</a>
                    </div>
                </div>
            {% empty %}
                <div class="card red darken-2 white-text">
                    <span class='card-title'>No Books in this Language</span>
                    <p>I wonder why we even have a record of this.</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/language_list.html
{% extends "catalog/base_index.html" %}

{% block content %}
<h3>Available Languages</h3>

{% for lang in language_list %}
    {% if forloop.first %}
        <div class="collection">
    {% endif %}
    <li class="collection-item"><a href="{{lang.get_absolute_url}}" class="black-text"><strong>{{lang.language}} </strong> <div class="right"> {{lang.books.count}} Books Available.</div></li>
    {% if forloop.last %}
        </div>
    {% endif %}
{% empty %}
    <h4>No Languages</h4>
    <div class="divider"> </div>
    <p>This is very weird.  This library has no books in known human languages.</p>
{% endfor %}
{% endblock %}